{
 "title": "Resource Utilization (Namespace)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "limit_resource",
    "query": "label_values(kube_resourcequota, resource)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_resourcequota, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Used Limits",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_resourcequota{namespace =~\"${namespace:pipe}\", resource=~\"${limit_resource:pipe}\", type=\"used\"}) by (namespace, resource) / sum(kube_resourcequota{namespace =~\"${namespace:pipe}\",resource=~\"${limit_resource:pipe}\", type=\"hard\"})by (namespace,resource)) * 100",
     "legendFormat": "{{namespace}} - {{resource}}"
    }
   ]
  }
 ]
}
{
 "title": "Resource Utilization (alerting)",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "limit_resource",
    "query": "label_values(kube_resourcequota, resource)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_resourcequota, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Limits Used %",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Consumed %" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_resourcequota{resource=~\".*memory\", type=\"used\"}) by (namespace, resource) / sum(kube_resourcequota{resource=~\".*memory\", type=\"hard\"})by (namespace,resource)) * 100",
     "legendFormat": "{{namespace}} - {{resource}} used %"
    }
   ]
  },
  {
   "title": "CPU Limit Used %",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent", "label": "Consumed %" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_resourcequota{resource=~\".*cpu\", type=\"used\"}) by (namespace, resource) / sum(kube_resourcequota{resource=~\".*cpu\", type=\"hard\"})by (namespace,resource)) * 100",
     "legendFormat": "{{namespace}} - {{resource}} used"
    }
   ]
  }
 ]
}
{
 "title": "Consul",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consul_0_pod_ip",
    "label": "consul_0_pod_ip",
    "query": "label_values(kube_pod_info{pod=~\"consul-server-0\"}, pod_ip)"
   },
   {
    "name": "consul_1_pod_ip",
    "label": "consul_1_pod_ip",
    "query": "label_values(kube_pod_info{pod=~\"consul-server-1\"}, pod_ip)"
   },
   {
    "name": "consul_2_pod_ip",
    "label": "consul_2_pod_ip",
    "query": "label_values(kube_pod_info{pod=~\"consul-server-2\"}, pod_ip)"
   },
   {
    "name": "Pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{pod=~\"consul-server-[0|1|2].*\"}, pod)"
   },
   {
    "name": "consul_0_host_ip",
    "label": "consul_0_host_ip",
    "query": "label_values(kube_pod_info{pod=~\"consul-server-0\"}, host_ip)"
   },
   {
    "name": "consul_1_host_ip",
    "label": "consul_1_host_ip",
    "query": "label_values(kube_pod_info{pod=~\"consul-server-1\"}, host_ip)"
   },
   {
    "name": "consul_2_host_ip",
    "label": "consul_2_host_ip",
    "query": "label_values(kube_pod_info{pod=~\"consul-server-2\"}, host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "$Pod Start Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "repeat": "Pod",
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=~\"$Pod\"}*1000"
    }
   ]
  },
  {
   "title": "$Pod Start Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=~\"$Pod\"}*1000"
    }
   ]
  },
  {
   "title": "$Pod Start Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=~\"$Pod\"}*1000"
    }
   ]
  },
  {
   "title": "consul-server-0 Pod IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$consul_0_pod_ip</span></h2>"
  },
  {
   "title": "consul-server-1 Pod IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 2 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$consul_1_pod_ip</span></h2>"
  },
  {
   "title": "consul-server-2 Pod IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$consul_2_pod_ip</span></h2>"
  },
  {
   "title": "consul-server-0 Host IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$consul_0_host_ip</span></h2>"
  },
  {
   "title": "consul-server-1 Host IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 4 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$consul_1_host_ip</span></h2>"
  },
  {
   "title": "consul-server-2 Host IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 4 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$consul_2_host_ip</span></h2>"
  },
  {
   "title": "Expected Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_current{namespace=~\"consul\"}"
    }
   ]
  },
  {
   "title": "Number Pods Running",
   "type": "singlestat",
   "description": "Number of containers running inside stateful set",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=\"consul-server\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"$Pod\", container_name!=\"POD\"}[5m]) * 100) by (pod_name)"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=\"consul-server-0\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}-0"
    },
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=\"consul-server-1\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}-1"
    },
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=\"consul-server-2\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}-2"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"consul-server-0\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}-0"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"consul-server-1\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}-1"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"consul-server-2\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}-2"
    }
   ]
  },
  {
   "title": "$Pod Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 18 },
   "repeat": "Pod",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod_name=\"$Pod\",container_name=\"consul\"}"
    }
   ]
  },
  {
   "title": "$Pod Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 18 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod_name=\"$Pod\",container_name=\"consul\"}"
    }
   ]
  },
  {
   "title": "$Pod Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 18 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod_name=\"$Pod\",container_name=\"consul\"}"
    }
   ]
  }
 ]
}
{
 "title": "Bitbucket",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bitbucket_0_pod_ip",
    "label": "bitbucket_0_pod_ip",
    "query": "label_values(kube_pod_info{pod=~\"bitbucket-0\"}, pod_ip)"
   },
   {
    "name": "bitbucket_1_pod_ip",
    "label": "bitbucket_1_pod_ip",
    "query": "label_values(kube_pod_info{pod=~\"bitbucket-1\"}, pod_ip)"
   },
   {
    "name": "Pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{pod=~\"bitbucket.*\"}, pod)"
   },
   {
    "name": "bitbucket_0_host_ip",
    "label": "bitbucket_0_host_ip",
    "query": "label_values(kube_pod_info{pod=~\"bitbucket-0\"}, host_ip)"
   },
   {
    "name": "bitbucket_1_host_ip",
    "label": "bitbucket_1_host_ip",
    "query": "label_values(kube_pod_info{pod=~\"bitbucket-1\"}, host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "$Pod Start Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "repeat": "Pod",
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=~\"$Pod\"}*1000"
    }
   ]
  },
  {
   "title": "$Pod Start Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=~\"$Pod\"}*1000"
    }
   ]
  },
  {
   "title": "bitbucket-1 Pod IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$bitbucket_1_pod_ip</span></h2>"
  },
  {
   "title": "bitbucket-0 Pod IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$bitbucket_0_pod_ip</span></h2>"
  },
  {
   "title": "bitbucket-1 Host IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$bitbucket_1_host_ip</span></h2>"
  },
  {
   "title": "bitbucket-0 Host IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$bitbucket_0_host_ip</span></h2>"
  },
  {
   "title": "Expected Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_current{namespace=~\"bitbucket\"}"
    }
   ]
  },
  {
   "title": "Number Pods Running",
   "type": "singlestat",
   "description": "Number of containers running inside stateful set",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=\"bitbucket\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"$Pod\", container_name!=\"POD\"}[5m]) * 100) by (pod_name)"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=\"bitbucket-0\", container_name=~\"bitbucket\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}-0"
    },
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=\"bitbucket-1\", container_name=~\"bitbucket\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}-1"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"bitbucket-0\", container=~\"bitbucket\"}",
     "legendFormat": "Requested: {{ container }}-0"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"bitbucket-1\", container=~\"bitbucket\"}",
     "legendFormat": "Requested: {{ container }}-1"
    }
   ]
  },
  {
   "title": "$Pod Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 18 },
   "repeat": "Pod",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod_name=\"$Pod\",container_name=\"bitbucket\"}"
    }
   ]
  },
  {
   "title": "$Pod Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 18 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod_name=\"$Pod\",container_name=\"bitbucket\"}"
    }
   ]
  }
 ]
}
{
 "title": "Jenkins",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jenkins_pod_ip",
    "label": "jenkins_pod_ip",
    "query": "label_values(kube_pod_info{pod=~\"jenkins-[^s|p].*\"}, pod_ip)"
   },
   {
    "name": "host_ip",
    "label": "host_ip",
    "query": "label_values(kube_pod_info{pod=~\"jenkins-[^s|p].*\"}, host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "jenkins_pod start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "jenkins_pod",
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=~\"jenkins-[^s|p].*\"}*1000"
    }
   ]
  },
  {
   "title": "jenkins_pod Pod IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "repeat": "jenkins_pod",
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$jenkins_pod_ip</span></h2>"
  },
  {
   "title": "jenkins_pod Host IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "repeat": "jenkins_pod",
   "content": "<h2 style=\"height:100%; text-align: center; display: flex; align-items: center; justify-content: center;\"><span style=\"color: #ff9900;\">$host_ip</span></h2>"
  },
  {
   "title": "number of jenkins containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "min",
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"jenkins-[^s|p].*\"})"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"jenkins-[^s|p].*\", container_name!=\"POD\"}[5m]) * 100) by (pod_name)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"jenkins-[^s|p].*\", container_name!=\"POD\"})"
    }
   ]
  }
 ]
}